export {default as HomePage} from './client/Home/homePage'
export {default as Login} from './client/Auth/login'
export {default as Register} from './client/Auth/register'
export {default as Product} from './client/Product/productList'
export {default as Detail} from './client/Detail/detailScreen'
export {default as Cart} from './client/Cart/cartScreen'
export {default as Checkout} from './client/Checkout/checkoutScreen'
export {default as CheckoutSuccess} from './client/Checkout/checkoutSuccess'

export {default as Order} from './client/Order/orderList'
export {default as OrderDetail} from './client/Order/orderDetail'
export {default as AddressScreen} from './client/Address/addressScreen'
export {default as FavoriteScreen} from './client/Favorite/favoriteScreen'
export {default as UpdateProfile} from './client/Account/updateProfile'
export {default as ClientResetPassword} from './client/Account/resetPassword'

export {default as DashBoard} from './admin/Dashboard/dashboard'
export {default as EmployeeScreen} from './admin/Employee/employeeScreen'
export {default as AddEditEmployee} from './admin/Employee/addEditEmployee'
export {default as EditPermission} from './admin/Employee/editPermission'
export {default as BrandScreen} from './admin/Brand/brandScreen'
export {default as CategoryScreen} from './admin/Category/categoryScreen'
export {default as ProductScreen} from './admin/Product/productScreen'
export {default as AddEditInfoProduct} from './admin/Product/Info/addEditScreen'
export {default as AddEditVersionProduct} from './admin/Product/Version/addEditScreen'
export {default as ImportScreen} from './admin/Import/importScreen'
export {default as AddImport} from './admin/Import/addImport'
export {default as DetailImport} from './admin/Import/detailImport'
export {default as CustomerScreen} from './admin/Customer/customerScreen'
export {default as EditCustomer} from './admin/Customer/editCustomer'
export {default as VoucherScreen} from './admin/Voucher/voucherScreen'
export {default as AddEditVoucher} from './admin/Voucher/addEditVoucher'
export {default as OrderScreen} from './admin/Order/orderScreen'
export {default as AdminOrderDetail} from './admin/Order/orderDetail'
export {default as ReviewScreen} from './admin/Review/reviewScreen'
export {default as AdminLogin} from './admin/Auth/login'
export {default as ForgotPasword} from './admin/Auth/forgotPassword'
export {default as ResetPassword} from './admin/Auth/resetPassword'
export {default as ChangePasswordScreen} from './admin/Profile/changePasswordScreen'


export {default as ShipperLogin} from './shipper/Auth/login'
export {default as ShipperOrdersPage} from './shipper/Order/orderList'
export {default as ShipperOrdersDetail} from './shipper/Detail/orderDetail'
export {default as ShipperHistoryPage} from './shipper/History/historyList'
export {default as ShipperNotifyPage} from './shipper/Notify/notifyScreen'
export {default as ShipperAccountPage} from './shipper/Account/accountScreen'

export {default as NotFound} from './Error/notFound'